//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientChat
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MessengerEntities : DbContext
    {
        private static MessengerEntities _context;

        public MessengerEntities()
            : base("name=MessengerEntities")
        {
        }
        
        public static MessengerEntities GetContext()
        {
            if (_context == null) _context = new MessengerEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auth> Auth { get; set; }
        public virtual DbSet<Chats> Chats { get; set; }
        public virtual DbSet<MessageFiles> MessageFiles { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<Requests> Requests { get; set; }
        public virtual DbSet<RequestStatus> RequestStatus { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TaskFiles> TaskFiles { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
        public virtual DbSet<TaskStatus> TaskStatus { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersChats> UsersChats { get; set; }
        public virtual DbSet<UserTask> UserTask { get; set; }
    }
}
