//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientChat.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int id { get; set; }
        public int ChatId { get; set; }
        public int from { get; set; }
        public string text { get; set; }
        public Nullable<int> Files { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Chats Chats { get; set; }
        public virtual MessageFiles MessageFiles { get; set; }
        public virtual Users Users { get; set; }
    }
}
